name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # specify your Node.js version here

    - name: Install Angular CLI
      run: npm install -g @angular/cli@17.0.1

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: ng build

    - name: Jasmine Unit Tests
      run: ng test --watch=false --browsers=ChromeHeadlessCI

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build -t tanmaysinghx/common-login:${{ github.sha }} .

    - name: Publish image to Docker Hub
      run: docker push tanmaysinghx/common-login:${{ github.sha }}
