name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Project
      run: npm run build

    - name: Jasmine Unit Tests
      run: ng test --watch=false --browsers=ChromeHeadlessCI

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build -t tanmaysinghx/common-login:${{ github.sha }} .

    - name: Publish image to Docker Hub

  # deploy:
  #   needs: build
  #   runs-on: aws-ec2
    # steps:
    #   - name: Pull Image from Docker Hub
    #     run: sudo docker pull tanmaysinghx/ts-app-auth-service:latest

    #   - name: Delete old container
    #     run: sudo docker rm -f ts-app-auth-service-container || true

    #   - name: Run Docker container
    #     run: sudo docker run -d -p 8080:8080 --name ts-app-auth-service-container tanmaysinghx/ts-app-auth-service:latest
